### ISSUE TITLE
Vấn đề gọi lại SDK

### ISSUE THREAD

**Issue by mannm123** [fpt-corp/fptai-chatbot-sdk#3]
Chào anh
Em hiện là sinh viên đang nghiên cứu tài liệu về fpt ai
Vậy nếu em đã xây dựng được fptai-chatbot-sdk thì làm sau để cho website em gọi lại được sdk này ạ
Ý là cần thay đổi những tham số nào trong đoạn scrift mà FPT cung cấp mẫu ạ
Em xin cảm ơn

**Comment by kimtuan1102** [comment]
Hi bạn. Ý bạn là sript trong phần settings của bot?

> Chào anh
> Em hiện là sinh viên đang nghiên cứu tài liệu về fpt ai
> Vậy nếu em đã xây dựng được fptai-chatbot-sdk thì làm sau để cho website em gọi lại được sdk này ạ
> Ý là cần thay đổi những tham số nào trong đoạn scrift mà FPT cung cấp mẫu ạ
> Em xin cảm ơn

Hi bạn, ý bạn là script trong phần settings của bot?
Nếu bạn đang xây dựng website. Thì bạn phải có một public url call back để engine bên mình trả kết  quả về. Tại đó bạn có thể sử dụng thêm websocket để xây dựng một ứng dụng chat hoàn chỉnh. Thanks

**Comment by mannm123** [comment]
Chào anh, ý em đang tính dựng 1 web hook bằng python cho con bot, em có đọc hướng dẫn trên fpt.ai nhưng không rõ thế nào để trang web có thể gọi để lấy câu trả lời từ bot server thông qua web hook
Em cảm ơn

**Comment by kimtuan1102** [comment]
> Chào anh, ý em đang tính dựng 1 web hook bằng python cho con bot, em có đọc hướng dẫn trên fpt.ai nhưng không rõ thế nào để trang web có thể gọi để lấy câu trả lời từ bot server thông qua web hook
> Em cảm ơn

Hi bạn. Trên docs mình đã viết khá rõ rồi. Cụ thể: bạn cần xây dưng một webhook và public webhook đó ra internet (Có thể dùng ngrok để test). Sau đó bạn tạo một con bot trên bot.fpt.ai. Trong phần cài đặt của bot bạn khai báo webhook api là địa chỉ public của webhook. Câu trả lời từ bot server trả về bằng cách sẽ gọi vào webhook của bạn. Tại đó bạn có thể phân tích kết quả trả về theo SDK nhé.

**Comment by mannm123** [comment]
Có thể cho em xin 1 con web hook mẫu được không ạ, hay nó chính là con fptaisdk python/java ạ
Em chân thành cảm ơn

**Comment by kimtuan1102** [comment]
> Có thể cho em xin 1 con web hook mẫu được không ạ, hay nó chính là con fptaisdk python/java ạ
> Em chân thành cảm ơn

Trong sdk mình đã có example cho webhook rồi. Đối với python nằm trong file app.py sử dụng framwork flask. Nó sẽ serve ra một cổng cụ thể. Sau đó bạn sử dụng ngrok để serve nó ra internet (Bạn có thể google thêm về ngrok). Địa chỉ ngrok serve ra chính là webhook nhé. Bạn sử dụng địa chỉ này để cấu hình trong phần webhook của bot nhé. https://docs.fpt.ai/docs/vi/conversation/documentation/bot-creator/settings#webhook

**Comment by mannm123** [comment]
em có xem về sdk của anh, v là mình chỉ cần fptai-sdk-python-example chứ không cần fptai-sdk-python-source phải không anh.

**Comment by kimtuan1102** [comment]
> em có xem về sdk của anh, v là mình chỉ cần fptai-sdk-python-example chứ không cần fptai-sdk-python-source phải không anh.

Đúng rồi bạn. Phần source là code của thư viện. Cho phép bạn có thể chỉnh sửa và viết thư viện của riêng mình.

**Comment by kimtuan1102** [comment]
issue reslove
